version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    image: cms_management/frontend:${PREFIX_ENV}
    container_name: frontend_container_${PREFIX_ENV}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_CONTAINER_PORT}"
    depends_on:
      - backend
    networks:
      - work_management

  backend:
    build:
      context: ./backend
    image: cms_management/backend:${PREFIX_ENV}
    container_name: backend_container_${PREFIX_ENV}
    ports:
      - "${BACKEND_PORT}:${BACKEND_CONTAINER_PORT}"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - DB_PORT=${DB_PORT}
    networks:
      - work_management

  db:
    image: postgres:latest
    container_name: database_container_${PREFIX_ENV}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - work_management

networks:
  work_management:
    driver: bridge
  default:
    driver: bridge
